### PR TITLE
feat!: add read function to use fileList only

### LINKED ISSUE #60: Move from filelist-from to filelist-utils

### PR DESCRIPTION
**Pull request by jobo322**
close: #60

### CODE REVIEW

**Comment by lpatiny** [comment]
Please check the tests as well

**Comment by jobo322** [comment]
> Please check the tests as well

The test cases are waiting for the new versions of jeol-data-test and jcamp-data-test

**Comment by targos** [comment]
@jobo322 I just merged some changes that I did on the main branch.

**Comment by lpatiny** [comment]
@jobo322 could you check that the tests are passing ?

**Pull request merged**
